CORONAVIRUS INFECTION PROBABILITY USING ML

In [9]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [5]:
data = pd.read_csv('I:/Jupyter Programs/randomdata.csv')
data.head()

Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough  \
0     101   65          1                   0          0        1      1   
1      98   59          0                   1          0        1      1   
2     103   46          0                   1          1        0      0   
3     104   83          0                   0          0        0      1   
4      98   98          0                   0          1        0      0   

   Probability  
0            1  
1            0  
2            0  
3            0  
4            0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 8 columns):
Fever                 1999 non-null int64
Age                   1999 non-null int64
 BodyPain             1999 non-null int64
DifficultyinBreath    1999 non-null int64
RunnyNose             1999 non-null int64
Travel                1999 non-null int64
Cough                 1999 non-null int64
Probability           1999 non-null int64
dtypes: int64(8)
memory usage: 125.1 KB


In [7]:
X = data.drop('Probability', axis=1)
print(X.head())
print('Data in Y')
Y = data['Probability']
Y.head()

   Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough
0     101   65          1                   0          0        1      1
1      98   59          0                   1          0        1      1
2     103   46          0                   1          1        0      0
3     104   83          0                   0          0        0      1
4      98   98          0                   0          1        0      0
Data in Y


0    1
1    0
2    0
3    0
4    0
Name: Probability, dtype: int64

In [10]:
#1 is affected and 0 is not affected
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.33, random_state = 5)


In [11]:
print(X_train.to_numpy())

[[101  16   1 ...   0   0   1]
 [ 98  25   1 ...   0   0   0]
 [104  53   0 ...   1   1   0]
 ...
 [103  63   0 ...   0   1   1]
 [104  38   1 ...   1   1   1]
 [ 98 100   0 ...   1   1   1]]


In [12]:
Y_train.to_numpy()

X_test.to_numpy()

Y_test.to_numpy()

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [13]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
Y_train_pred = clf.fit(X_train, Y_train)

C:\new\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
infection = clf.predict([[98, 20, 0, 1, 0, 0, 0]])
infection_probability = clf.predict_proba([[98, 20, 0, 1, 0, 0, 0]])
print(infection)
print(infection_probability)

[0]
[[0.51703992 0.48296008]]
